// 育英祭OS — サンプルデータ（デモ表示用）

export const festival = {
  name: '育英祭',
  year: '2026',
  hours: '10:00 - 15:30',
}

// 混雑ステータス
export const STATUS = {
  free: { label: '空いている', color: '#34d399' },
  normal: { label: '普通', color: '#fbbf24' },
  busy: { label: '混んでいる', color: '#f87171' },
  soldout: { label: '売り切れ', color: '#f472b6' },
  closed: { label: '一時停止', color: '#94a3b8' },
}

// カテゴリ色
export const CATEGORY = {
  フード: '#fb923c',
  ドリンク: '#38bdf8',
  ゲーム: '#a78bfa',
  展示: '#60a5fa',
  ステージ: '#f472b6',
}

export const FLOORS = ['1F', '2F', '3F']

// 出店データ
export const shops = [
  {
    id: 's1',
    room: '1-A教室',
    name: '育英カレー食堂',
    org: '3年3組',
    category: 'フード',
    status: 'busy',
    floor: '1F',
    price: '¥400',
    wait: '約15分',
    comment: 'スパイス香る本格カレー！',
  },
  {
    id: 's2',
    room: '1-B教室',
    name: 'クレープ夢工房',
    org: '2年4組',
    category: 'フード',
    status: 'normal',
    floor: '1F',
    price: '¥350',
    wait: '約8分',
    comment: '20種類のトッピングから選べます',
  },
  {
    id: 's3',
    room: '1-C教室',
    name: '射的屋台',
    org: '1年3組',
    category: 'ゲーム',
    status: 'normal',
    floor: '1F',
    price: '¥300',
    wait: '約3分',
    comment: '景品まだまだあります🎁',
  },
  {
    id: 's4',
    room: '1-D教室',
    name: 'たこ焼きスタンド',
    org: '3年5組',
    category: 'フード',
    status: 'soldout',
    floor: '1F',
    price: '¥300',
    wait: '—',
    comment: '本日分は完売しました',
  },
  {
    id: 's5',
    room: '1-E教室',
    name: '焼きそば屋',
    org: '2年1組',
    category: 'フード',
    status: 'normal',
    floor: '1F',
    price: '¥400',
    wait: '約5分',
    comment: 'ソース・塩から選べます',
  },
  {
    id: 's6',
    room: '中庭',
    name: 'ラムネ釣り',
    org: '1年1組',
    category: 'ゲーム',
    status: 'free',
    floor: '1F',
    price: '¥200',
    wait: '約1分',
    comment: '今ならすぐ遊べます！',
  },
  {
    id: 's7',
    room: '体育館',
    name: '軽音ライブ',
    org: '軽音部',
    category: 'ステージ',
    status: 'busy',
    floor: '1F',
    price: '無料',
    wait: '次回 13:30〜',
    comment: '人気バンドが続々登場',
  },
  {
    id: 's8',
    room: '体育館',
    name: 'ダンスステージ',
    org: 'ダンス部',
    category: 'ステージ',
    status: 'closed',
    floor: '1F',
    price: '無料',
    wait: '次回 14:00〜',
    comment: '転換のため一時停止中',
  },
  {
    id: 's9',
    room: '2-B教室',
    name: '書道作品展',
    org: '書道部',
    category: '展示',
    status: 'free',
    floor: '2F',
    price: '無料',
    wait: '約1分',
    comment: '体験コーナーは随時受付中',
  },
  {
    id: 's10',
    room: '2-C教室',
    name: '科学マジックショー',
    org: '科学部',
    category: '展示',
    status: 'normal',
    floor: '2F',
    price: '無料',
    wait: '約10分',
    comment: '毎時30分にショー開催',
  },
  {
    id: 's11',
    room: '3-A教室',
    name: '鉄道ジオラマ展',
    org: '鉄道研究部',
    category: '展示',
    status: 'free',
    floor: '3F',
    price: '無料',
    wait: '約2分',
    comment: '毎時00分にデモ運行🚆',
  },
  {
    id: 's12',
    room: '3-B教室',
    name: 'VRゲーム体験',
    org: 'パソコン部',
    category: 'ゲーム',
    status: 'busy',
    floor: '3F',
    price: '¥500',
    wait: '約20分',
    comment: '最新VRが体験できる',
  },
  {
    id: 's13',
    room: '3-C教室',
    name: '喫茶ノスタルジア',
    org: '2年2組',
    category: 'ドリンク',
    status: 'normal',
    floor: '3F',
    price: '¥300',
    wait: '約7分',
    comment: 'レトロ空間でひと休み',
  },
]

// お知らせデータ（新しい順）
export const notices = [
  {
    id: 'n1',
    level: 'important',
    time: '5/19 12:40',
    title: '体育館ステージ 10分遅れています',
    body: '軽音バンドの転換に時間がかかっており、次のステージ開始が10分遅れています。少々お待ちください。',
  },
  {
    id: 'n2',
    level: 'info',
    time: '5/19 12:30',
    title: '3年5組 たこ焼き 売り切れ',
    body: '本日分のたこ焼きは完売しました。ご来場ありがとうございました！',
  },
  {
    id: 'n3',
    level: 'info',
    time: '5/19 11:00',
    title: '落とし物のお知らせ',
    body: '落とし物・忘れ物は職員室前のカウンターにて受付しております。',
  },
  {
    id: 'n4',
    level: 'important',
    time: '5/19 10:30',
    title: '迷子のお知らせ',
    body: '迷子になった場合は、近くのスタッフ（赤いスタッフTシャツ）にお声がけください。',
  },
  {
    id: 'n5',
    level: 'info',
    time: '5/19 09:00',
    title: '本日のスケジュール',
    body: '10:00 開会式 / 11:00 各出店オープン / 13:30 軽音ライブ / 14:00 ダンスステージ / 15:30 閉会式',
  },
]
